### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by ryandesign** [ferdinandl007/TouchBarPong#2]
You've only made available a compiled application, without the source code. You should make the source code available here.

**Comment by ferdinandl007** [comment]
The project is not really open source yet  😬  so that is the reason why the source code hasn't been published yet however it will after the sales on the app store have quiet down a bit once this happens I will publish it ☺️ also the app store version of the game has all ready been developed much further with much more features and functions

**Comment by ryandesign** [comment]
If it's not open source, it doesn't belong on GitHub.
